[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
week1_challenge = "73zUmjohyBGgv7JvqguwzENwrTensYbVk3WoZHMSrM2j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"
# test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
